name: Publish to registry.npmjs.org

on:
  workflow_call:
    secrets:
      BOT_GITHUB_TOKEN:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Download a single artifact
      uses: actions/download-artifact@v4
      with:
        name: raxb-xmlsec-wasm
        path: dist
    - name: Display structure of downloaded files
      run: ls -R dist
    - run: npm publish --provenance --access public
      working-directory: ./dist
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release:
      name: Release
      runs-on: ubuntu-latest
      needs: publish
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Release
          uses: actions/create-release@latest
          env:
            GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            draft: true
            prerelease: false